#!/bin/sh

case "$1" in
    start)
        echo "Loading scull, fault and helloworld driver"
        scull_load.sh
        ;;
    stop)
        echo "Unloading scull, fault and helloworld driver"
        scull_unload.sh
        ;;
    *)
        echo "usage: $0 {start|stop}"
        exit 1
esac
exit 0

