#!/bin/sh

case "$1" in
    start)
        echo "Loading scull, fault and helloworld driver"
        module_load.sh faulty
        modprobe hello
        ;;
    stop)
        echo "Unloading scull, fault and helloworld driver"
        module_unload.sh faulty
        rmmod hello
        ;;
    *)
        echo "usage: $0 {start|stop}"
        exit 1
esac
exit 0

